# Get a copy of docker running 
# Build Dockerfile.dev
# Run test suite
# Deploy code to AWS
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Dockerfile.dev
        run: docker build -t geoffreyma92/docker-react -f Dockerfile.dev .
      - name: Run test in container
        run: docker run -e CI=true geoffreyma92/docker-react npm run test
      - name: Deploy to AWS Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: 12345
          deployment_package: deploy.zip
          region: ap-southeast-2
        
    
        
        
    
      
    

  
